version: '3.8'

services:
  shutter-mcp-server:
    build: .
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

